version: "3.8"

services:
  db_graphql:
    image: postgres:13-alpine
    env_file:
      - envs/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
    postgres_data: